import os
import sys

# Add the local path since we're testing
sys.path.append(os.getcwd())

from mcp_server import mcp

# This is just a basic wrapper for local testing without the MCP protocol
if __name__ == "__main__":
    print("Testing generate_pptx tool directly...")
    
    # We will import the tool function directly since FastMCP wraps it
    # FastMCP stores tools in its `_tools` list or similar
    # In newer FastMCP, it's just registered. 
    
    test_code = """
from pptx import Presentation

prs = Presentation()
title_slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(title_slide_layout)
title = slide.shapes.title
subtitle = slide.placeholders[1]

title.text = "Hello, World!"
subtitle.text = "Generated by MCP Server"

prs.save("output.pptx")
"""

    print("Running generated code...")
    # Get the original function. We have it in mcp_server module.
    import mcp_server
    
    # Actually, we can just call mcp_server.generate_pptx 
    # if we didn't wrap it weirdly.
    # The decorator `@mcp.tool()` usually preserves the function or creates a Tool object.
    
    # Let's see what type it is
    if callable(mcp_server.generate_pptx):
        result = mcp_server.generate_pptx(test_code)
    else:
        # It might be a Tool object. In FastMCP, it's typically still callable, 
        # or accessible via the mcp object.
        pass
        
    print(f"Result: {result}")
